#!/usr/bin/python3
def raise_exception():
    a, b =  6 , 's'
    c = a + b
    print("{}".format(c))
